-- camim_fin.fin_despesa — replica de vw_Fin_Despesa dos 13 postos
-- Filtros no ETL: [Valor pago] IS NOT NULL AND idContaTipo <> 11 AND [Data de pagamento] >= 2020-01-01
-- Incremental: MAX(id_despesa) por posto

CREATE TABLE IF NOT EXISTS fin_despesa (
  posto                     CHAR(1)         NOT NULL,
  id_despesa                INTEGER         NOT NULL,
  valor_devido              NUMERIC(14,2),
  valor_pago                NUMERIC(14,2),
  data_vencimento           TIMESTAMP,
  data_pagamento            TIMESTAMP,
  data_cancelamento         TIMESTAMP,
  descricao                 VARCHAR(100),
  comentario                TEXT,
  tipo                      VARCHAR(50),
  plano                     VARCHAR(50),
  corretor                  VARCHAR(50),
  cobrador                  VARCHAR(50),
  medico                    VARCHAR(50),
  conta                     VARCHAR(50),
  situacao                  VARCHAR(9),
  talao                     INTEGER,
  valor_fatura              NUMERIC(14,2),
  cliente                   VARCHAR(100),
  matricula                 BIGINT,
  funcionario               VARCHAR(50),
  confere                   BOOLEAN,
  pessoa                    VARCHAR(50),
  id_conta                  INTEGER,
  data_prestacao            TIMESTAMP,
  id_conta_tipo             INTEGER,
  id_lancamento             INTEGER,
  usuario                   VARCHAR(50),
  paciente                  VARCHAR(100),
  ordem_pagamento           INTEGER,
  contabilizado             BOOLEAN,
  plano_principal           VARCHAR(50),
  fornecedor                VARCHAR(50),
  endereco                  VARCHAR(50),
  id_funcionario            INTEGER,
  id_medico                 INTEGER,
  usuario_inclusao          VARCHAR(50),
  marcado                   BOOLEAN,
  valor_rateio              NUMERIC(14,2),
  possui_rateio             VARCHAR(3),
  id_forma                  INTEGER,
  forma                     VARCHAR(50),
  digitou_talao             BOOLEAN,
  valor_medico_ctrlq        NUMERIC(14,2),
  data_atendimento          TIMESTAMP,
  sistema_medico_inclusao   BOOLEAN,
  quantidade_anexo          INTEGER,
  possui_anexo              BOOLEAN,
  carteira_do_medico        BOOLEAN,
  link_boleto_medico        VARCHAR(1000),
  cargo                     VARCHAR(7),
  atendido                  BOOLEAN,
  sub_corretor              VARCHAR(100),
  data_agendamento          TIMESTAMP,
  conta_bancaria            VARCHAR(50),
  pagamento_online          BOOLEAN,
  data_agendamento_medico   TIMESTAMP,
  imported_at               TIMESTAMP       NOT NULL DEFAULT NOW(),
  PRIMARY KEY (posto, id_despesa)
);

CREATE INDEX IF NOT EXISTS ix_fin_despesa_data_pagamento ON fin_despesa(data_pagamento);
CREATE INDEX IF NOT EXISTS ix_fin_despesa_posto          ON fin_despesa(posto);
CREATE INDEX IF NOT EXISTS ix_fin_despesa_id_cliente     ON fin_despesa(cliente);
CREATE INDEX IF NOT EXISTS ix_fin_despesa_tipo           ON fin_despesa(tipo);
